on: pull_request

name: Unit tests
jobs:
  test_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: compile
        run: go build
      - name: run go test
        run: go test -v ./...
